# Configuración general de la aplicación
spring.application.name=producto-service
app.version=0.7.0
app.api.version=v1

# Puerto del servidor
server.port=8080

# Configuración de la base de datos
spring.datasource.url=jdbc:postgresql://localhost:5432/curso_springboot
spring.datasource.username=devdb
spring.datasource.password=a1b2c3
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de JPA
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Configuración de Actuator
management.server.port=8081
management.endpoints.web.exposure.include=*

# Endpoints disponibles:
# /actuator/health - Estado de salud
# /actuator/info - Información de la app
# /actuator/metrics - Métricas
# /actuator/beans - Beans de Spring
# /actuator/env - Variables de entorno